imedge		:	imedge.c ImageStuff.c ImageStuff.h
				gcc imedge.c ImageStuff.c -o imedge -lpthread -lm

imedgeMC	:	imedgeMC.c ImageStuff.c ImageStuff.h
				gcc imedgeMC.c ImageStuff.c -o imedgeMC -lpthread -lm