imedge		:	imedge.c ImageStuff.c ImageStuff.h
				gcc imedge.c ImageStuff.c -o imedge -lpthread -lm

imedgeMC	:	imedgeMC.c ImageStuff.c ImageStuff.h
				gcc imedgeMC.c ImageStuff.c -o imedgeMC -lpthread -lm

imedgeMCT	:	imedgeMCT.c ImageStuff.c ImageStuff.h
				gcc imedgeMCT.c ImageStuff.c -o imedgeMCT -lpthread -lm
