imrotate	:	imrotate.c ImageStuff.c ImageStuff.h
				gcc imrotate.c ImageStuff.c -o imrotate -lpthread -lm

imrotateMC	:	imrotateMC.c ImageStuff.c ImageStuff.h
				gcc imrotateMC.c ImageStuff.c -o imrotateMC -lpthread -lm
	